git_hash: 2e561015e28cd0a1390717ac01fd420b3d1ff6f5
model_class: TimeDistributedEfficientNet
species:
- aardvark
- antelope_duiker
- badger
- bat
- bird
- blank
- cattle
- cheetah
- chimpanzee_bonobo
- civet_genet
- elephant
- equid
- forest_buffalo
- fox
- giraffe
- gorilla
- hare_rabbit
- hippopotamus
- hog
- human
- hyena
- large_flightless_bird
- leopard
- lion
- mongoose
- monkey_prosimian
- pangolin
- porcupine
- reptile
- rodent
- small_cat
- wild_dog_jackal
starting_learning_rate: 0.001584893192461114
train_config:
  auto_lr_find: true
  backbone_finetune_config:
    backbone_initial_ratio_lr: 0.01
    multiplier: 1
    pre_train_bn: true
    train_bn: false
    unfreeze_backbone_at_epoch: 3
    verbose: true
  batch_size: 1
  cache_dir: /home/ubuntu/.cache/zamba
  checkpoint: null
  data_directory: /home/ubuntu/zamba-algorithms
  dry_run: false
  early_stopping_config:
    mode: max
    monitor: val_macro_f1
    patience: 5
    verbose: true
  from_scratch: true
  gpus: 1
  max_epochs: null
  model_name: time_distributed
  num_workers: 5
  overwrite_save_dir: false
  predict_all_zamba_species: true
  save_dir: experiments/td_small_set_full_size_mdlite
  scheduler_config:
    scheduler: MultiStepLR
    scheduler_params:
      gamma: 0.5
      milestones:
      - 3
      verbose: true
  skip_load_validation: true
  split_proportions: null
  weight_download_region: us
training_start_time: '2021-09-29T23:50:09.687298'
video_loader_config:
  crop_bottom_pixels: 50
  early_bias: false
  ensure_total_frames: true
  evenly_sample_total_frames: false
  fps: 4.0
  frame_indices: null
  frame_selection_height: null
  frame_selection_width: null
  i_frames: false
  megadetector_lite_config:
    confidence: 0.25
    device: cuda
    fill_mode: score_sorted
    image_height: 416
    image_width: 416
    n_frames: 16
    nms_threshold: 0.45
    seed: 55
    sort_by_time: true
  model_input_height: 240
  model_input_width: 426
  pix_fmt: rgb24
  scene_threshold: null
  total_frames: 16
